services:
  web:
    image: ghcr.io/cedar2025/xboard:new
    volumes:
      - ./:/www/
    environment:
      - docker=true
    ports:
      - "8080:8080"
    command: php artisan octane:start --port=8080 --host=0.0.0.0
    restart: always
  queue:
    image: ghcr.io/cedar2025/xboard:new
    volumes:
      - ./:/www/
    restart: always
    command: php artisan queue:work --tries=3
